name: deploy.yml
on:
  push:
  workflow_dispatch:

jobs:
  build_gorgustranslatorweb:
    uses: ./.github/workflows/build.yml

  deploy:
    needs: build_gorgustranslatorweb
    if: ${{ github.event_name != 'workflow-call' && github.ref == 'main' }}
    runs-on: ubuntu-latest

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Download Build Artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ needs.build_gorgustranslatorweb.outputs.ARTIFACT }}

      - name: Upload Page Artifacts
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'build/'

      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v4