name: Deploy to GitHub Pages

on:
  push:
    branches:
      - "main"
  workflow_dispatch:

env:
  EM_VERSION: 4.0.5
  #EM_CACHE_FOLDER: "emsdk-cache"
  USE_CCACHE: 'false'
  CCACHE_DIR: "ccache-dir"
  PYTHON_VERSION: '3.14'

jobs:
  build_site:
    runs-on: ubuntu-latest
    steps:
      - name: Update APT
        run: sudo apt-get update

      - name: Install CCache
        if: env.USE_CCACHE == 'true'
        run: sudo apt-get install ccache -y

      - name: Setup cache
        id: cache-em-cache
        uses: actions/cache@v4
        with:
          path: |
            emsdk
            ${{env.EM_CACHE_FOLDER}}
          key: emsdk-${{env.EM_VERSION}}-${{ runner.os }}

      #- name: Setup EMSDK
      #  uses: mymindstorm/setup-emsdk@v14
      #  with:
      #    version: ${{env.EM_VERSION}}
      #    actions-cache-folder: ${{env.EM_CACHE_FOLDER}}
      #    no-cache: 'true'

      - name: Checkout EMSDK
        if: steps.cache-em-cache.outputs.cache-hit != 'true'
        uses: actions/checkout@v4
        with:
          repository: 'emscripten-core/emsdk'
          path: "emsdk"

      - name: Setup EMSDK
        if: steps.cache-em-cache.outputs.cache-hit != 'true'
        run: |
          cd emsdk
          ./emsdk install ${{ env.EM_VERSION }}
          ./emsdk activate ${{ env.EM_VERSION }}
          cd ..

      # needs to be set manually.
      # downside is we need to update this whenever EMSDK updates. particularly the node version.
      # unfortunately, sourcing the EMSDK Env setup script doesn't work.
      - name: Add EMSDK to Environment
        run: |
          EMSDK_CMD=1 ./emsdk construct_env
          sed -i "s/SET //g" emsdk_set_env.bat
          mv emsdk_set_env.bat emsdk_set_env
          cat emsdk_set_env >> $GITHUB_ENV

      - name: Print PATH
        run: echo $PATH

      - name: Use CCache
        if: env.USE_CCACHE == 'true'
        run: export EM_COMPILER_WRAPPER=ccache CCACHE_DIR=${{ env.CCACHE_DIR }}

      - name: Checkout
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 23
          cache: pnpm

      - name: Checkout Python
        if: ${{ env.PYTHON_VERSION != '3.14' }}
        uses: actions/checkout@v4
        with:
          repository: 'python/cpython'
          path: "cpython"
          ref: ${{ env.PYTHON_VERSION }}

      - name: Checkout Python (No Explict Ref)
        if: ${{ env.PYTHON_VERSION == '3.14' }}
        uses: actions/checkout@v4
        with:
          repository: 'python/cpython'
          path: "cpython"

      - name: Download and apply "picnixz"'s "fix/build/hacl-emscripten-133042" branch
        run: |
          cd ${{ github.workspace }}/cpython
          wget -O emscriptenFixBuildPatch.patch https://patch-diff.githubusercontent.com/raw/python/cpython/pull/133064.patch
          git apply --index emscriptenFixBuildPatch.patch
          cd ..

      - name: Build Emscripten CPython
        run: |
          cd cpython
          python Tools/wasm/emscripten build
          cd ..

      - name: Install dependencies
        run: pnpm install

      - name: Copy Emscripten Python
        run: |
          cp cpython/cross-build/wasm32-emscripten/build/python/web_example/python${{ env.PYTHON_VERSION }}.zip  static
          cp cpython/cross-build/wasm32-emscripten/build/python/python.wasm                                      static
          cp cpython/cross-build/wasm32-emscripten/build/python/python.mjs                                       static

      - name: build
        env:
          BASE_PATH: '/${{ github.event.repository.name }}'
        run: |
          pnpm run build

      - name: Upload Artifacts
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'build/'

  deploy:
    needs: build_site
    runs-on: ubuntu-latest

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v4