name: Deploy to Github Pages
on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      updateGorgusTranslator:
        description: "Update Gorgus Translator"
        required: true
        default: false
        type: boolean
      gorgusTranslatorRepo:
        description: "Gorgus Translator Repository"
        required: true
        default: "https://github.com/SpookyDervish/Gorgus-Translator.git"
        type: string
      gorgusTranslatorBranch:
        description: "Gorgus Translator Branch"
        required: true
        default: "main"
        type: string

jobs:
  build_gorgustranslatorweb:
    uses: ./.github/workflows/build.yml
    with:
      updateGorgusTranslator: ${{ github.event_name == 'workflow_dispatch' && inputs.updateGorgusTranslator || false }}
      gorgusTranslatorRepo: ${{ github.event_name == 'workflow_dispatch' && inputs.gorgusTranslatorRepo || 'https://github.com/SpookyDervish/Gorgus-Translator.git' }}
      gorgusTranslatorBranch: ${{ github.event_name == 'workflow_dispatch' && inputs.gorgusTranslatorBranch || 'main' }}

  deploy:
    needs: build_gorgustranslatorweb
    runs-on: ubuntu-latest

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Download Build Artifact
        id: download-build-artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ needs.build_gorgustranslatorweb.outputs.ARTIFACT }}

      - name: Upload Page Artifacts
        uses: actions/upload-pages-artifact@v3
        with:
          path: '${{ steps.download-build-artifact.outputs.download-path }}/'

      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v4